name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    strategy:
      matrix:
        java: [ '8' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build Compiler with Maven
        run: mvn -B package --file compiler/pom.xml
      - name: Build CreaProPhone with J2MEcompiler
        run: -|
          java -jar compiler/target/j2mecompiler-1.0-SNAPSHOT.jar
          ls
          mv CreaProPhone.jar $GITHUB_WORKSPACE/
          ls $GITHUB_WORKSPACE
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CreaProPhone
          path: CreaProPhone.jar