name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    strategy:
      matrix:
        java: [ '8' ]
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant
      - name: Build App
        run: ant -f build.xml jar
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: CreaProPhone
          path: dist/*.jar
      - name: Attach Jar to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*.jar
